<?php
/**
 * Readabler
 * Web accessibility for Your WordPress site.
 * Exclusively on https://1.envato.market/readabler
 *
 * @encoding        UTF-8
 * @version         1.6.5
 * @copyright       (C) 2018 - 2023 Merkulove ( https://merkulov.design/ ). All rights reserved.
 * @license         Envato License https://1.envato.market/KYbje
 * @contributors    Nemirovskiy Vitaliy (nemirovskiyvitaliy@gmail.com), Dmitry Merkulov (dmitry@merkulov.design)
 * @support         help@merkulov.design
 * @license         Envato License https://1.envato.market/KYbje
 **/

namespace Merkulove\Readabler;

/**
 * @package Readabler
 */
final class Numbers {

	/**
	 * Translation of numbers from one to 200
	 */
	static function translation(): array {

		return array(

			esc_html__( 'zero', 'readabler' ),
			esc_html__( 'one', 'readabler' ),
			esc_html__( 'two', 'readabler' ),
			esc_html__( 'three', 'readabler' ),
			esc_html__( 'four', 'readabler' ),
			esc_html__( 'five', 'readabler' ),
			esc_html__( 'six', 'readabler' ),
			esc_html__( 'seven', 'readabler' ),
			esc_html__( 'eight', 'readabler' ),
			esc_html__( 'nine', 'readabler' ),
			esc_html__( 'ten', 'readabler' ),
			esc_html__( 'eleven', 'readabler' ),
			esc_html__( 'twelve', 'readabler' ),
			esc_html__( 'thirteen', 'readabler' ),
			esc_html__( 'fourteen', 'readabler' ),
			esc_html__( 'fifteen', 'readabler' ),
			esc_html__( 'sixteen', 'readabler' ),
			esc_html__( 'seventeen', 'readabler' ),
			esc_html__( 'eighteen', 'readabler' ),
			esc_html__( 'nineteen', 'readabler' ),
			esc_html__( 'twenty', 'readabler' ),
			esc_html__( 'twenty one', 'readabler' ),
			esc_html__( 'twenty two', 'readabler' ),
			esc_html__( 'twenty three', 'readabler' ),
			esc_html__( 'twenty four', 'readabler' ),
			esc_html__( 'twenty five', 'readabler' ),
			esc_html__( 'twenty six', 'readabler' ),
			esc_html__( 'twenty seven', 'readabler' ),
			esc_html__( 'twenty eight', 'readabler' ),
			esc_html__( 'twenty nine', 'readabler' ),
			esc_html__( 'thirty', 'readabler' ),
			esc_html__( 'thirty one', 'readabler' ),
			esc_html__( 'thirty two', 'readabler' ),
			esc_html__( 'thirty three', 'readabler' ),
			esc_html__( 'thirty four', 'readabler' ),
			esc_html__( 'thirty five', 'readabler' ),
			esc_html__( 'thirty six', 'readabler' ),
			esc_html__( 'thirty seven', 'readabler' ),
			esc_html__( 'thirty eight', 'readabler' ),
			esc_html__( 'thirty nine', 'readabler' ),
			esc_html__( 'forty', 'readabler' ),
			esc_html__( 'forty one', 'readabler' ),
			esc_html__( 'forty two', 'readabler' ),
			esc_html__( 'forty three', 'readabler' ),
			esc_html__( 'forty four', 'readabler' ),
			esc_html__( 'forty five', 'readabler' ),
			esc_html__( 'forty six', 'readabler' ),
			esc_html__( 'forty seven', 'readabler' ),
			esc_html__( 'forty eight', 'readabler' ),
			esc_html__( 'forty nine', 'readabler' ),
			esc_html__( 'fifty', 'readabler' ),
			esc_html__( 'fifty one', 'readabler' ),
			esc_html__( 'fifty two', 'readabler' ),
			esc_html__( 'fifty three', 'readabler' ),
			esc_html__( 'fifty four', 'readabler' ),
			esc_html__( 'fifty five', 'readabler' ),
			esc_html__( 'fifty six', 'readabler' ),
			esc_html__( 'fifty seven', 'readabler' ),
			esc_html__( 'fifty eight', 'readabler' ),
			esc_html__( 'fifty nine', 'readabler' ),
			esc_html__( 'sixty', 'readabler' ),
			esc_html__( 'sixty one', 'readabler' ),
			esc_html__( 'sixty two', 'readabler' ),
			esc_html__( 'sixty three', 'readabler' ),
			esc_html__( 'sixty four', 'readabler' ),
			esc_html__( 'sixty five', 'readabler' ),
			esc_html__( 'sixty six', 'readabler' ),
			esc_html__( 'sixty seven', 'readabler' ),
			esc_html__( 'sixty eight', 'readabler' ),
			esc_html__( 'sixty nine', 'readabler' ),
			esc_html__( 'seventy', 'readabler' ),
			esc_html__( 'seventy one', 'readabler' ),
			esc_html__( 'seventy two', 'readabler' ),
			esc_html__( 'seventy three', 'readabler' ),
			esc_html__( 'seventy four', 'readabler' ),
			esc_html__( 'seventy five', 'readabler' ),
			esc_html__( 'seventy six', 'readabler' ),
			esc_html__( 'seventy seven', 'readabler' ),
			esc_html__( 'seventy eight', 'readabler' ),
			esc_html__( 'seventy nine', 'readabler' ),
			esc_html__( 'eighty', 'readabler' ),
			esc_html__( 'eighty one', 'readabler' ),
			esc_html__( 'eighty two', 'readabler' ),
			esc_html__( 'eighty three', 'readabler' ),
			esc_html__( 'eighty four', 'readabler' ),
			esc_html__( 'eighty five', 'readabler' ),
			esc_html__( 'eighty six', 'readabler' ),
			esc_html__( 'eighty seven', 'readabler' ),
			esc_html__( 'eighty eight', 'readabler' ),
			esc_html__( 'eighty nine', 'readabler' ),
			esc_html__( 'ninety', 'readabler' ),
			esc_html__( 'ninety one', 'readabler' ),
			esc_html__( 'ninety two', 'readabler' ),
			esc_html__( 'ninety three', 'readabler' ),
			esc_html__( 'ninety four', 'readabler' ),
			esc_html__( 'ninety five', 'readabler' ),
			esc_html__( 'ninety six', 'readabler' ),
			esc_html__( 'ninety seven', 'readabler' ),
			esc_html__( 'ninety eight', 'readabler' ),
			esc_html__( 'ninety nine', 'readabler' ),
			esc_html__( 'one hundred', 'readabler' ),
			esc_html__( 'one hundred one', 'readabler' ),
			esc_html__( 'one hundred two', 'readabler' ),
			esc_html__( 'one hundred three', 'readabler' ),
			esc_html__( 'one hundred four', 'readabler' ),
			esc_html__( 'one hundred five', 'readabler' ),
			esc_html__( 'one hundred six', 'readabler' ),
			esc_html__( 'one hundred seven', 'readabler' ),
			esc_html__( 'one hundred eight', 'readabler' ),
			esc_html__( 'one hundred nine', 'readabler' ),
			esc_html__( 'one hundred ten', 'readabler' ),
			esc_html__( 'one hundred eleven', 'readabler' ),
			esc_html__( 'one hundred twelve', 'readabler' ),
			esc_html__( 'one hundred thirteen', 'readabler' ),
			esc_html__( 'one hundred fourteen', 'readabler' ),
			esc_html__( 'one hundred fifteen', 'readabler' ),
			esc_html__( 'one hundred sixteen', 'readabler' ),
			esc_html__( 'one hundred seventeen', 'readabler' ),
			esc_html__( 'one hundred eighteen', 'readabler' ),
			esc_html__( 'one hundred nineteen', 'readabler' ),
			esc_html__( 'one hundred twenty', 'readabler' ),
			esc_html__( 'one hundred twenty one', 'readabler' ),
			esc_html__( 'one hundred twenty two', 'readabler' ),
			esc_html__( 'one hundred twenty three', 'readabler' ),
			esc_html__( 'one hundred twenty four', 'readabler' ),
			esc_html__( 'one hundred twenty five', 'readabler' ),
			esc_html__( 'one hundred twenty six', 'readabler' ),
			esc_html__( 'one hundred twenty seven', 'readabler' ),
			esc_html__( 'one hundred twenty eight', 'readabler' ),
			esc_html__( 'one hundred twenty nine', 'readabler' ),
			esc_html__( 'one hundred thirty', 'readabler' ),
			esc_html__( 'one hundred thirty one', 'readabler' ),
			esc_html__( 'one hundred thirty two', 'readabler' ),
			esc_html__( 'one hundred thirty three', 'readabler' ),
			esc_html__( 'one hundred thirty four', 'readabler' ),
			esc_html__( 'one hundred thirty five', 'readabler' ),
			esc_html__( 'one hundred thirty six', 'readabler' ),
			esc_html__( 'one hundred thirty seven', 'readabler' ),
			esc_html__( 'one hundred thirty eight', 'readabler' ),
			esc_html__( 'one hundred thirty nine', 'readabler' ),
			esc_html__( 'one hundred forty', 'readabler' ),
			esc_html__( 'one hundred forty one', 'readabler' ),
			esc_html__( 'one hundred forty two', 'readabler' ),
			esc_html__( 'one hundred forty three', 'readabler' ),
			esc_html__( 'one hundred forty four', 'readabler' ),
			esc_html__( 'one hundred forty five', 'readabler' ),
			esc_html__( 'one hundred forty six', 'readabler' ),
			esc_html__( 'one hundred forty seven', 'readabler' ),
			esc_html__( 'one hundred forty eight', 'readabler' ),
			esc_html__( 'one hundred forty nine', 'readabler' ),
			esc_html__( 'one hundred fifty', 'readabler' ),
			esc_html__( 'one hundred fifty one', 'readabler' ),
			esc_html__( 'one hundred fifty two', 'readabler' ),
			esc_html__( 'one hundred fifty three', 'readabler' ),
			esc_html__( 'one hundred fifty four', 'readabler' ),
			esc_html__( 'one hundred fifty five', 'readabler' ),
			esc_html__( 'one hundred fifty six', 'readabler' ),
			esc_html__( 'one hundred fifty seven', 'readabler' ),
			esc_html__( 'one hundred fifty eight', 'readabler' ),
			esc_html__( 'one hundred fifty nine', 'readabler' ),
			esc_html__( 'one hundred sixty', 'readabler' ),
			esc_html__( 'one hundred sixty one', 'readabler' ),
			esc_html__( 'one hundred sixty two', 'readabler' ),
			esc_html__( 'one hundred sixty three', 'readabler' ),
			esc_html__( 'one hundred sixty four', 'readabler' ),
			esc_html__( 'one hundred sixty five', 'readabler' ),
			esc_html__( 'one hundred sixty six', 'readabler' ),
			esc_html__( 'one hundred sixty seven', 'readabler' ),
			esc_html__( 'one hundred sixty eight', 'readabler' ),
			esc_html__( 'one hundred sixty nine', 'readabler' ),
			esc_html__( 'one hundred seventy', 'readabler' ),
			esc_html__( 'one hundred seventy one', 'readabler' ),
			esc_html__( 'one hundred seventy two', 'readabler' ),
			esc_html__( 'one hundred seventy three', 'readabler' ),
			esc_html__( 'one hundred seventy four', 'readabler' ),
			esc_html__( 'one hundred seventy five', 'readabler' ),
			esc_html__( 'one hundred seventy six', 'readabler' ),
			esc_html__( 'one hundred seventy seven', 'readabler' ),
			esc_html__( 'one hundred seventy eight', 'readabler' ),
			esc_html__( 'one hundred seventy nine', 'readabler' ),
			esc_html__( 'one hundred eighty', 'readabler' ),
			esc_html__( 'one hundred eighty one', 'readabler' ),
			esc_html__( 'one hundred eighty two', 'readabler' ),
			esc_html__( 'one hundred eighty three', 'readabler' ),
			esc_html__( 'one hundred eighty four', 'readabler' ),
			esc_html__( 'one hundred eighty five', 'readabler' ),
			esc_html__( 'one hundred eighty six', 'readabler' ),
			esc_html__( 'one hundred eighty seven', 'readabler' ),
			esc_html__( 'one hundred eighty eight', 'readabler' ),
			esc_html__( 'one hundred eighty nine', 'readabler' ),
			esc_html__( 'one hundred ninety', 'readabler' ),
			esc_html__( 'one hundred ninety one', 'readabler' ),
			esc_html__( 'one hundred ninety two', 'readabler' ),
			esc_html__( 'one hundred ninety three', 'readabler' ),
			esc_html__( 'one hundred ninety four', 'readabler' ),
			esc_html__( 'one hundred ninety five', 'readabler' ),
			esc_html__( 'one hundred ninety six', 'readabler' ),
			esc_html__( 'one hundred ninety seven', 'readabler' ),
			esc_html__( 'one hundred ninety eight', 'readabler' ),
			esc_html__( 'one hundred ninety nine', 'readabler' ),
			esc_html__( 'two hundred', 'readabler' )

		);

	}

}
